export const PUBLIC_ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  OTP_VERIFY: "/otp-verify",
  RESET_PASSWORD: "/reset-password",
};

export const PRIVATE_ROUTES = {
  DASHBOARD: "/dashboard",
  USERS: "/users",
  USERS_LIST: "/users/list",
  USERS_VIEW: "/users/view",
  DASHBOARD_CRM: "/dashboard/crm",
  INVOICES_LIST: "/invoices/list",
  INVOICES_PREVIEW: "/invoices/preview",
  INVOICES_ADD: "/invoices/add",
  INVOICES_EDIT: "/invoices/edit",
  DASHBOARD_ANALYTICS: "/dashboard/analytics",
  USERS_VIEW_ACCOUNT: "/users/view/account",
  USERS_VIEW_SECURITY: "/users/view/security",
  USERS_VIEW_BILLING: "/users/view/billing",
  USERS_VIEW_NOTIFICATIONS: "/users/view/notifications",
  USERS_VIEW_CONNECTIONS: "/users/view/connections",
  TRANSACTIONS_LIST: "/transactions/list",
  SUBSCRIPTIONS_LIST: "/subscriptions/list",
  SUBSCRIPTIONS_VIEW: "/subscriptions/view",
  BADGES: "/badges",
  BADGES_LIST: "/badges/list",
  BADGES_ADD: "/badges/add",
  BADGES_EDIT: "/badges/edit",
  COMPANIES: "/companies",
  COMPANIES_LIST: "/companies/list",
  COMPANIES_VIEW: "/companies/view",
  COMPANIES_VIEW_JOBS: "/companies/view/jobs",
  COMPANIES_VIEW_EVENTS: "/companies/view/events",
  COMPANIES_VIEW_BUSINESS: "/companies/view/businessleads",
  COMPANIES_VIEW_HIRING: "/companies/view/hiring",
  COMPANIES_VIEW_ENGAGEMENT: "/companies/view/engagement",
  COMPANIES_VIEW_SPONSORSHIP: "/companies/view/sponsorship",
  COMPANIES_VIEW_BOOST: "/companies/view/boost",
  COMPANIES_VIEW_GROWTH: "/companies/view/companygrowth",
  PROMO_CODES_LIST: "/promo-codes/list",
  EVENTS_LIST: "/events/list",
  GROUPS_LIST: "/groups/list",
};
export const ROUTES = {
  ...PUBLIC_ROUTES,
  ...PRIVATE_ROUTES,
};
